name: "Debian Package Generation"

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v1.*'
      - 'v1.*.*'

jobs:
  Debian-Package-Branch-Preperation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - run: git fetch --prune --unshallow --tags
      - run: python ./tools/prepare_packaging.py
      - run: git checkout -b pack-tmp
      - run: git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: git config --local user.name "github-actions[bot]"
      - run: cp -r deps/mdnsd deps/mdnsd_back
      - run: cp -r deps/ua-nodeset deps/ua-nodeset_back
      - run: git rm -rf --cached deps/mdnsd
      - run: git rm -rf --cached deps/ua-nodeset
      - run: mv deps/mdnsd_back deps/mdnsd
      - run: rm -rf deps/mdnsd/.git
      - run: mv deps/ua-nodeset_back deps/ua-nodeset
      - run: rm -rf deps/ua-nodeset/.git
      - run: rm -rf .gitmodules
      - run: git add deps/*
      - run: git add debian/*
      - run: git add CMakeLists.txt
      - run: git commit -m "[ci skip] Pack with inline submodules"
      - name: Branch name
        run: echo running on branch pack/${GITHUB_REF##*/}
      - name: Get the current branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF##*/}"
        id: myref
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: pack/${{ steps.myref.outputs.branch }}
          force: true
